# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Faisal Nur
#tagline:             'Portofolio, Blog Pribadi, dan Hal Lainnya'
description:         'Kadang menulis untuk orang lain, lebih sering menulis untuk diri sendiri.'
url:                 faisalnur.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Faisal Nur
  url:               https://twitter.com/mfaisalni
  email:             mfaisalni@gmail.com

# Custom vars
version:             1.0.0
